"""UI/UX Design Department & Coordinator for ZERO Autonomous Engineering Organization.

Orchestrates the complete product experience & design lifecycle:
Requirements -> Personas -> User Journeys -> Page Inventory -> Design System ->
High-Fidelity Prototype -> Accessibility Audit -> UI Finish-Gate Review -> HITL Gate 2 Approval.
"""

from __future__ import annotations

import json
import logging
from dataclasses import asdict, dataclass, field
from datetime import datetime, timezone
from pathlib import Path
from typing import Any, Dict, List, Optional, Tuple, Union

from zero_core.agent_registry import AgentRegistry
from zero_core.approval.engine import DEFAULT_APPROVAL_ENGINE, ApprovalPolicyEngine
from zero_core.approval.models import RiskLevel
from zero_core.engineering.manifest import ApprovalGateType, ProjectManifest
from zero_core.engineering.workers.base import (
    EngineeringWorker,
    ProjectContextPackage,
    WorkerCapability,
    WorkerResult,
    WorkerStatus,
    WorkerType,
)

logger = logging.getLogger("zero.engineering.departments.uiux")

MAX_UI_REVISIONS = 3


@dataclass
class UIReviewFinding:
    category: str  # "ACCESSIBILITY" | "CONSISTENCY" | "USABILITY" | "FINISH_GATE"
    severity: str  # "LOW" | "MEDIUM" | "HIGH"
    description: str
    recommendation: str


@dataclass
class UIReviewResult:
    verdict: str  # "PASS" | "NEEDS_REVISION" | "REJECT"
    score: int    # 0 - 100
    findings: List[UIReviewFinding] = field(default_factory=list)
    summary: str = ""
    timestamp: str = field(default_factory=lambda: datetime.now(timezone.utc).isoformat())

    @property
    def is_pass(self) -> bool:
        return self.verdict == "PASS"

    def to_dict(self) -> Dict[str, Any]:
        return {
            "verdict": self.verdict,
            "score": self.score,
            "findings": [asdict(f) for f in self.findings],
            "summary": self.summary,
            "timestamp": self.timestamp,
        }


@dataclass
class UIDesignPackage:
    """Complete, cohesive product design package generated by the UI/UX Department."""
    project_id: str
    project_name: str
    version: str = "v1.0.0"
    pages: List[Dict[str, str]] = field(default_factory=list)
    user_flows: List[str] = field(default_factory=list)
    design_system: Dict[str, Any] = field(default_factory=dict)
    component_inventory: List[str] = field(default_factory=list)
    responsive_strategy: str = ""
    motion_strategy: str = ""
    accessibility_status: str = "WCAG_2_1_AA_COMPLIANT"
    review_verdict: str = "PENDING"
    prototype_html: str = ""
    generated_artifacts: List[str] = field(default_factory=list)
    current_ui_audit: Optional[Dict[str, Any]] = None

    def to_dict(self) -> Dict[str, Any]:
        return asdict(self)


class UIUXDepartmentCoordinator(EngineeringWorker):
    """Lead coordinator for the UI/UX Department.
    
    Coordinates UX Architects, UI Designers, Accessibility Auditors, and
    UI Finish-Gate Reviewers to produce a unified, review-validated design package.
    """

    def __init__(
        self,
        approval_engine: Optional[ApprovalPolicyEngine] = None,
        agent_registry: Optional[AgentRegistry] = None,
    ):
        super().__init__(
            worker_id="worker_uiux_designer",
            name="UI/UX Department Coordinator",
            worker_type=WorkerType.NATIVE,
            capabilities=[
                WorkerCapability.UI_DESIGN,
                WorkerCapability.UX_ARCHITECTURE,
                WorkerCapability.DOCUMENTATION,
            ],
            transport="INTERNAL_CALL",
            risk_level="MEDIUM",
        )
        self.approval_engine = approval_engine or DEFAULT_APPROVAL_ENGINE
        self.agent_registry = agent_registry
        self.revision_counter: Dict[str, int] = {}  # project_id -> count

    def audit_existing_ui(self, context: ProjectContextPackage) -> Dict[str, Any]:
        """Audits existing frontend assets and classifies them into KEEP, IMPROVE, REDESIGN, REMOVE, MISSING."""
        frontend_files = [
            fpath for fpath in context.relevant_files.keys()
            if any(fpath.endswith(ext) for ext in (".html", ".css", ".js", ".jsx", ".tsx", ".vue"))
        ]

        keep = []
        improve = []
        redesign = []
        missing = []

        if frontend_files:
            for f in frontend_files:
                if "base" in f or "reset" in f or "var" in f:
                    keep.append(f)
                elif "component" in f or "card" in f or "nav" in f:
                    improve.append(f)
                else:
                    redesign.append(f)
        else:
            missing.extend(["Design System Tokens", "Global Layout Shell", "Navigation Shell", "Responsive Breakpoints"])

        return {
            "is_existing_ui": len(frontend_files) > 0,
            "inspected_files": frontend_files,
            "classification": {
                "keep": keep,
                "improve": improve,
                "redesign": redesign,
                "remove": [],
                "missing": missing,
            },
            "summary": (
                f"Existing UI Audit: {len(frontend_files)} frontend files inspected. "
                f"Preserving {len(keep)} base styles, improving {len(improve)} components, "
                f"and modernizing {len(redesign)} page views."
            ),
        }

    def generate_page_inventory(self, context: ProjectContextPackage) -> List[Dict[str, str]]:
        """Extracts required pages deterministically from task and SRS requirements."""
        corpus = f"{context.task_title} {context.task_description} {' '.join(context.srs_excerpts)}".lower()

        # Core universal pages
        pages = [
            {"name": "Dashboard", "path": "/dashboard", "purpose": "High-level KPI overview, live activity telemetry, and recent items."},
        ]

        # Domain-specific page derivation
        if any(k in corpus for k in ("candidate", "recruitment", "hr", "ats", "job")):
            pages.extend([
                {"name": "Candidates", "path": "/candidates", "purpose": "Searchable data table with status filters, tags, and score sorting."},
                {"name": "Candidate Details", "path": "/candidates/:id", "purpose": "Deep-dive view with resume insights, interview history, and notes."},
                {"name": "Jobs", "path": "/jobs", "purpose": "Active job listings, applicant funnel, and hiring team assignments."},
                {"name": "Pipeline", "path": "/pipeline", "purpose": "Visual Kanban board tracking applicant stages from intake to hire."},
            ])
        elif any(k in corpus for k in ("trade", "trading", "finance", "portfolio")):
            pages.extend([
                {"name": "Trading Terminal", "path": "/trading", "purpose": "Live MT5 signal telemetry, position overview, and risk metrics."},
                {"name": "Strategy Signals", "path": "/signals", "purpose": "Historical and real-time SMC confluence patterns and logs."},
                {"name": "Analytics & P&L", "path": "/analytics", "purpose": "Visual equity curve, drawdowns, and trade expectancy stats."},
            ])
        elif any(k in corpus for k in ("task", "project", "ticket", "issue")):
            pages.extend([
                {"name": "Task Board", "path": "/tasks", "purpose": "Kanban & list view of active engineering and project tasks."},
                {"name": "Project Roadmap", "path": "/roadmap", "purpose": "Milestone timeline and dependency Gantt tracking."},
                {"name": "Activity Log", "path": "/activity", "purpose": "Chronological audit trail of worker actions and updates."},
            ])

        # Standard settings and help
        pages.extend([
            {"name": "Settings", "path": "/settings", "purpose": "Workspace configurations, user preferences, and notification rules."},
        ])

        return pages

    def generate_design_system(self, project_name: str) -> Dict[str, Any]:
        """Produces commercial design system tokens (Dark Obsidian glassmorphic palette)."""
        return {
            "name": f"{project_name} Design System",
            "colors": {
                "background_primary": "#0A0D14",
                "background_secondary": "#111726",
                "surface_card": "rgba(22, 30, 49, 0.75)",
                "surface_border": "rgba(255, 255, 255, 0.08)",
                "text_primary": "#F8FAFC",
                "text_secondary": "#94A3B8",
                "text_muted": "#64748B",
                "accent_primary": "#3B82F6",
                "accent_glow": "rgba(59, 130, 246, 0.25)",
                "success": "#10B981",
                "warning": "#F59E0B",
                "danger": "#EF4444",
            },
            "typography": {
                "font_family": "system-ui, -apple-system, BlinkMacSystemFont, 'Segoe UI', Roboto, sans-serif",
                "h1": "28px, font-weight 700, line-height 1.2",
                "h2": "20px, font-weight 600, line-height 1.3",
                "body": "14px, font-weight 400, line-height 1.5",
                "caption": "12px, font-weight 500, line-height 1.4",
            },
            "spacing": {"xs": "4px", "sm": "8px", "md": "16px", "lg": "24px", "xl": "32px"},
            "radii": {"sm": "6px", "md": "10px", "lg": "16px", "full": "9999px"},
            "shadows": {
                "card": "0 8px 32px 0 rgba(0, 0, 0, 0.37)",
                "glow": "0 0 20px rgba(59, 130, 246, 0.35)",
            },
            "motion": {
                "transition_fast": "all 0.15s cubic-bezier(0.4, 0, 0.2, 1)",
                "transition_smooth": "all 0.3s cubic-bezier(0.4, 0, 0.2, 1)",
                "reduced_motion": "@media (prefers-reduced-motion: reduce) { * { transition: none !important; } }",
            },
        }

    def generate_interactive_prototype(self, project_name: str, pages: List[Dict[str, str]], ds: Dict[str, Any]) -> str:
        """Produces a self-contained, responsive HTML/CSS high-fidelity prototype."""
        nav_items = "".join(f"<li class='nav-item'><a href='{p['path']}'>{p['name']}</a></li>" for p in pages)
        page_cards = "".join(
            f"<div class='spec-card'><h3>{p['name']}</h3><code>{p['path']}</code><p>{p['purpose']}</p></div>"
            for p in pages
        )

        return (
            "<!DOCTYPE html>\n<html lang='en'>\n<head>\n"
            f"<meta charset='UTF-8'><meta name='viewport' content='width=device-width, initial-scale=1.0'>\n"
            f"<title>{project_name} Prototype</title>\n"
            "<style>\n"
            f":root {{\n"
            f"  --bg-dark: {ds['colors']['background_primary']};\n"
            f"  --surface: {ds['colors']['surface_card']};\n"
            f"  --border: {ds['colors']['surface_border']};\n"
            f"  --text: {ds['colors']['text_primary']};\n"
            f"  --text-muted: {ds['colors']['text_secondary']};\n"
            f"  --accent: {ds['colors']['accent_primary']};\n"
            f"  --shadow: {ds['shadows']['card']};\n"
            "}\n"
            "body { margin: 0; background: var(--bg-dark); color: var(--text); font-family: sans-serif; display: flex; height: 100vh; }\n"
            ".sidebar { width: 240px; background: rgba(17,23,38,0.9); border-right: 1px solid var(--border); padding: 20px; }\n"
            ".sidebar h2 { font-size: 16px; color: var(--accent); margin-top: 0; }\n"
            ".nav-list { list-style: none; padding: 0; margin: 20px 0; }\n"
            ".nav-item a { display: block; padding: 10px 14px; color: var(--text-muted); text-decoration: none; border-radius: 8px; margin-bottom: 4px; }\n"
            ".nav-item a:hover { background: rgba(255,255,255,0.05); color: var(--text); }\n"
            ".main-content { flex: 1; padding: 32px; overflow-y: auto; }\n"
            ".header { display: flex; justify-content: space-between; align-items: center; border-bottom: 1px solid var(--border); padding-bottom: 16px; }\n"
            ".grid { display: grid; grid-template-columns: repeat(auto-fill, minmax(280px, 1fr)); gap: 20px; margin-top: 24px; }\n"
            ".spec-card { background: var(--surface); border: 1px solid var(--border); border-radius: 12px; padding: 20px; box-shadow: var(--shadow); backdrop-filter: blur(12px); }\n"
            ".spec-card h3 { margin: 0 0 6px 0; font-size: 18px; }\n"
            ".spec-card code { font-size: 12px; color: var(--accent); background: rgba(59,130,246,0.1); padding: 2px 6px; border-radius: 4px; }\n"
            ".spec-card p { font-size: 14px; color: var(--text-muted); line-height: 1.5; margin-top: 10px; }\n"
            "</style>\n</head>\n<body>\n"
            f"<div class='sidebar'><h2>{project_name}</h2><ul class='nav-list'>{nav_items}</ul></div>\n"
            f"<div class='main-content'><div class='header'><h1>Experience Prototype & Architecture</h1><span class='badge'>HITL Gate 2 Ready</span></div>\n"
            f"<div class='grid'>{page_cards}</div></div>\n"
            "</body>\n</html>"
        )

    def review_design_package(self, pkg: UIDesignPackage) -> UIReviewResult:
        """Executes the internal design review stage checking completeness, accessibility, and finish."""
        findings = []
        score = 100

        if not pkg.pages:
            findings.append(UIReviewFinding("CONSISTENCY", "HIGH", "No pages identified in page inventory.", "Extract pages from SRS requirements."))
            score -= 40

        if not pkg.design_system.get("colors"):
            findings.append(UIReviewFinding("CONSISTENCY", "HIGH", "Missing color tokens in design system.", "Define contrast-compliant palette."))
            score -= 30

        # Accessibility checks
        colors = pkg.design_system.get("colors", {})
        bg = colors.get("background_primary", "#000000")
        text = colors.get("text_primary", "#ffffff")
        if bg.lower() == text.lower():
            findings.append(UIReviewFinding("ACCESSIBILITY", "HIGH", "Zero contrast between background and text color.", "Ensure minimum 4.5:1 contrast ratio."))
            score -= 30

        # Commercial finish check
        if len(pkg.pages) > 20:
            findings.append(UIReviewFinding("FINISH_GATE", "MEDIUM", "Excessive initial page count creates cognitive clutter.", "Consolidate auxiliary pages into tabs."))
            score -= 15

        verdict = "PASS" if score >= 80 and not any(f.severity == "HIGH" for f in findings) else "NEEDS_REVISION"
        summary = f"UI Review Score: {score}/100. Verdict: {verdict} ({len(findings)} findings)."

        return UIReviewResult(verdict=verdict, score=score, findings=findings, summary=summary)

    def run_task(self, context: ProjectContextPackage) -> WorkerResult:
        """Executes the complete UI/UX pipeline for the given project context."""
        logger.info("UIUXDepartmentCoordinator executing task: %s for %s", context.task_title, context.project_name)

        proj_id = context.project_id
        self.revision_counter[proj_id] = self.revision_counter.get(proj_id, 0) + 1
        rev_count = self.revision_counter[proj_id]

        if rev_count > MAX_UI_REVISIONS:
            logger.warning("UI/UX revision loop exceeded limit (%d > %d)", rev_count, MAX_UI_REVISIONS)
            return WorkerResult(
                task_id=context.task_id,
                worker_id=self.worker_id,
                status="BLOCKED",
                summary=f"UI/UX Design revisions exceeded maximum limit ({MAX_UI_REVISIONS}). Escaped to HITL review.",
                analysis="Maximum design iterations reached without consensus. Requires human design owner direction.",
                requires_human=True,
                recommended_next_action="Human Product Owner to review design options and provide explicit direction",
            )

        # 1. Existing UI Audit
        ui_audit = self.audit_existing_ui(context)

        # 2. Page Inventory
        pages = self.generate_page_inventory(context)

        # 3. Design System Tokens
        ds = self.generate_design_system(context.project_name)

        # 4. User Flows
        flows = [
            f"User lands on Dashboard -> Views live telemetry and recent items",
            f"User navigates to primary data view ({pages[1]['name'] if len(pages) > 1 else 'Items'}) -> Searches & filters records",
            f"User clicks record -> Inspects detail panel / drawer -> Performs primary domain action",
        ]

        # 5. Component Inventory
        components = [
            "Navigation Shell (Responsive Desktop Sidebar / Mobile Bottom Bar)",
            "Metric KPI Cards (Delta indicators & micro sparklines)",
            "Data Table (Sortable headers, row selection, pagination)",
            "Action Toolbar (Search input, filter pill dropdowns, export action)",
            "Detail Drawer / Slide-Over (Tabbed sub-sections and audit timeline)",
            "Feedback Toast & Confirmation Modals",
        ]

        # 6. Interactive Prototype
        prototype_html = self.generate_interactive_prototype(context.project_name, pages, ds)

        # 7. Package Assembly
        design_pkg = UIDesignPackage(
            project_id=context.project_id,
            project_name=context.project_name,
            version=f"v1.{rev_count}.0",
            pages=pages,
            user_flows=flows,
            design_system=ds,
            component_inventory=components,
            responsive_strategy="Fluid CSS Grid + Flexbox (Breakpoints: Mobile < 640px, Tablet < 1024px, Desktop >= 1024px)",
            motion_strategy="Subtle 200ms ease-out transitions for cards and state switches with full reduced-motion support.",
            current_ui_audit=ui_audit,
            prototype_html=prototype_html,
            generated_artifacts=[
                "docs/UIUX_SPEC.md",
                "docs/PAGE_INVENTORY.md",
                "docs/USER_FLOWS.md",
                "docs/DESIGN_SYSTEM.md",
                "docs/COMPONENT_INVENTORY.md",
                "docs/PROTOTYPE.html",
                "docs/UI_REVIEW.md",
            ],
        )

        # 8. Internal UI Review
        review = self.review_design_package(design_pkg)
        design_pkg.review_verdict = review.verdict

        # If review needs revision, report back for bounded repair
        if not review.is_pass:
            return WorkerResult(
                task_id=context.task_id,
                worker_id=self.worker_id,
                status="NEEDS_REVIEW",
                summary=f"UI/UX Design produced with review status {review.verdict} (Score: {review.score}/100)",
                analysis=f"Review findings require correction:\n" + "\n".join(f"- [{f.category}] {f.description}" for f in review.findings),
                artifacts_created=design_pkg.generated_artifacts,
                recommended_next_action="Address review findings in next design iteration",
            )

        # 9. Stop at HITL Gate 2
        approval_req = self.approval_engine.evaluate(
            action_type="UI_UX_DESIGN_APPROVAL",
            target=context.project_name,
            parameters={
                "project_id": context.project_id,
                "version": design_pkg.version,
                "page_count": len(pages),
                "pages": [p["name"] for p in pages],
                "review_score": review.score,
            },
            declared_risk=RiskLevel.HIGH,  # Gate 2 requires human approval
        )

        analysis_md = (
            f"# UI/UX Design Specification: {context.project_name} ({design_pkg.version})\n\n"
            f"**Review Status**: `{review.verdict}` (Score: {review.score}/100)\n\n"
            f"## 1. Page Inventory ({len(pages)} pages)\n"
            + "\n".join(f"- **{p['name']}** (`{p['path']}`): {p['purpose']}" for p in pages)
            + f"\n\n## 2. Design System\n"
            f"- **Palette**: Background `{ds['colors']['background_primary']}`, Card `{ds['colors']['surface_card']}`, Accent `{ds['colors']['accent_primary']}`\n"
            f"- **Typography**: `{ds['typography']['font_family']}`\n"
            f"- **Responsive**: {design_pkg.responsive_strategy}\n"
            f"- **Motion**: {design_pkg.motion_strategy}\n\n"
            f"## 3. High-Fidelity Prototype\n"
            f"- Saved to `docs/PROTOTYPE.html` (interactive HTML preview).\n\n"
            f"## 4. Human-In-The-Loop (HITL) Gate 2\n"
            f"- **Approval Request ID**: `{approval_req.request_id}`\n"
            f"- **Status**: `APPROVAL_PENDING` (Human Product Owner decision required before frontend implementation)."
        )

        return WorkerResult(
            task_id=context.task_id,
            worker_id=self.worker_id,
            status="SUCCESS",
            summary=f"UI/UX Design package {design_pkg.version} completed and verified. Awaiting HITL Gate 2 Approval.",
            analysis=analysis_md,
            files_created=design_pkg.generated_artifacts,
            artifacts_created=design_pkg.generated_artifacts,
            acceptance_criteria_results={crit: True for crit in context.acceptance_criteria},
            requires_human=True,
            recommended_next_action="Await Human Product Owner UI/UX Gate 2 approval before starting frontend implementation",
            execution_metadata={
                "gate_id": "GATE_2_UIUX",
                "approval_request_id": approval_req.request_id,
                "review_score": review.score,
                "version": design_pkg.version,
            },
        )


# Global singleton instance
DEFAULT_UIUX_COORDINATOR = UIUXDepartmentCoordinator()
