"""Project Builder Agent for ZERO (Milestone M15 & Autonomous Builder Pipeline).

Orchestrates the complete software engineering inception & scaffolding pipeline:
Idea -> Requirements/SRS -> Architecture -> ADRs -> Folder Structure -> Scaffold Files on Disk.
"""

from __future__ import annotations

import os
import uuid
from dataclasses import asdict, dataclass, field
from datetime import datetime, timezone
from pathlib import Path
from typing import Any, Dict, List, Optional


@dataclass
class ProjectBlueprint:
    """Represents a fully structured project architectural blueprint."""
    blueprint_id: str
    project_name: str
    idea_summary: str
    srs_requirements: Dict[str, List[str]]
    architecture_layers: List[str]
    adrs: List[Dict[str, str]]
    folder_structure: List[str]
    roadmap_milestones: List[Dict[str, str]]
    created_at: str = field(
        default_factory=lambda: datetime.now(timezone.utc).isoformat()
    )

    def to_markdown(self) -> str:
        """Renders the blueprint as a full specification document."""
        lines = [
            f"# Architectural Blueprint: {self.project_name}",
            f"*Generated by ZERO Project Builder*: {self.created_at}",
            "",
            "## 1. Idea & Problem Definition",
            self.idea_summary,
            "",
            "## 2. Software Requirements Specification (SRS)",
            "### Functional Requirements:",
        ]
        for req in self.srs_requirements.get("functional", []):
            lines.append(f"- {req}")

        lines.append("\n### Non-Functional Requirements:")
        for req in self.srs_requirements.get("non_functional", []):
            lines.append(f"- {req}")

        lines.append("\n## 3. Core Architecture & Layers")
        for layer in self.architecture_layers:
            lines.append(f"- **{layer}**")

        lines.append("\n## 4. Architecture Decision Records (ADRs)")
        for adr in self.adrs:
            lines.append(f"### {adr.get('title', 'ADR')}")
            lines.append(f"- **Decision**: {adr.get('decision', '')}")
            lines.append(f"- **Rationale**: {adr.get('rationale', '')}")

        lines.append("\n## 5. Target Folder Structure")
        lines.append("```text")
        for f in self.folder_structure:
            lines.append(f)
        lines.append("```")

        lines.append("\n## 6. Implementation Roadmap")
        for m in self.roadmap_milestones:
            lines.append(f"- **{m.get('milestone', 'M')}**: {m.get('description', '')}")

        return "\n".join(lines)


class ProjectBuilderAgent:
    """Native Project Builder Agent executing the Idea -> Architecture -> Scaffold pipeline."""

    def generate_srs(self, project_name: str, idea: str) -> Dict[str, List[str]]:
        """Produces structured functional and non-functional requirements."""
        return {
            "functional": [
                f"FR-01: Core domain orchestration for {project_name}.",
                "FR-02: Deterministic, framework-independent business logic handlers.",
                "FR-03: Multi-channel intake interface (API / CLI / Webhook).",
                "FR-04: Secure credential management and least-privilege role boundaries.",
            ],
            "non_functional": [
                "NFR-PERF-01: Low-latency response times under 100ms for core routing.",
                "NFR-REL-01: 100% automated test coverage without network flakiness.",
                "NFR-SEC-01: Strict secret sanitization and audit logging.",
            ],
        }

    def generate_architecture_layers(self, project_name: str) -> List[str]:
        """Defines the clean architecture layered model."""
        return [
            f"Interface Layer (CLI / FastAPI / Webhook) for {project_name}",
            "Application & Orchestration Layer (State Machine / Task Coordinator)",
            "Domain & Business Logic Core (Pure Python, zero-external dependencies)",
            "Data & Integration Adapters (PostgreSQL / Redis / External APIs)",
            "Observability & Telemetry (Structured JSON Logging & Tracing)",
        ]

    def generate_adrs(self, project_name: str) -> List[Dict[str, str]]:
        """Generates standard ADRs for the new system."""
        return [
            {
                "title": "ADR-001: Clean Modular Architecture",
                "decision": f"Keep {project_name} decoupled into core domain vs integration adapters.",
                "rationale": "Allows painless testability with synthetic fixtures and zero mock hallucinations.",
            },
            {
                "title": "ADR-002: Least Privilege Security Model",
                "decision": "Enforce read-only roles and approval gates for mutating operations.",
                "rationale": "Prevents unauthorized mutations and maintains total user trust.",
            },
        ]

    def generate_folder_structure(self, project_name: str) -> List[str]:
        """Generates standard folder layout."""
        slug = project_name.lower().replace(" ", "_").replace("-", "_")
        return [
            f"{slug}/",
            f"├── {slug}_core/",
            "│   ├── __init__.py",
            "│   ├── config.py",
            "│   ├── orchestrator.py",
            "│   ├── domain/",
            "│   ├── adapters/",
            "│   └── interfaces/",
            "├── tests/",
            "│   └── test_core.py",
            "├── docs/",
            "│   ├── SRS.md",
            "│   ├── ARCHITECTURE.md",
            "│   └── ROADMAP.md",
            "├── scripts/",
            "├── requirements.txt",
            "└── README.md",
        ]

    def generate_roadmap(self) -> List[Dict[str, str]]:
        """Produces standard milestone sequence."""
        return [
            {"milestone": "M1 — Formalization", "description": "SRS, Architecture, ADRs, Folder Structure."},
            {"milestone": "M2 — Core Logic", "description": "Deterministic domain engine and unit test suite."},
            {"milestone": "M3 — Integration Adapters", "description": "Database, external API, and tool connectors."},
            {"milestone": "M4 — Interface & Observability", "description": "FastAPI web endpoints and structured logging."},
            {"milestone": "M5 — Deployment", "description": "Containerization and background service runners."},
        ]

    def build_blueprint(self, project_name: str, idea: str) -> ProjectBlueprint:
        """Executes the full pipeline generating an end-to-end blueprint."""
        blueprint_id = f"bp_{uuid.uuid4().hex[:8]}"
        srs = self.generate_srs(project_name, idea)
        layers = self.generate_architecture_layers(project_name)
        adrs = self.generate_adrs(project_name)
        folders = self.generate_folder_structure(project_name)
        roadmap = self.generate_roadmap()

        return ProjectBlueprint(
            blueprint_id=blueprint_id,
            project_name=project_name,
            idea_summary=idea,
            srs_requirements=srs,
            architecture_layers=layers,
            adrs=adrs,
            folder_structure=folders,
            roadmap_milestones=roadmap,
        )

    def scaffold_project(self, project_name: str, target_dir: Path, idea: str = "") -> Dict[str, Any]:
        """Scaffolds a real project directory on disk with specification docs and starter code."""
        slug = project_name.lower().replace(" ", "_").replace("-", "_")
        root = target_dir / slug if target_dir.name != slug else target_dir
        root.mkdir(parents=True, exist_ok=True)

        blueprint = self.build_blueprint(project_name, idea or f"Autonomous system for {project_name}")

        # 1. Write Docs
        docs_dir = root / "docs"
        docs_dir.mkdir(exist_ok=True)
        (docs_dir / "SRS.md").write_text(
            f"# Software Requirements Specification (SRS): {project_name}\n\n"
            + "\n".join(f"- {r}" for r in blueprint.srs_requirements["functional"]),
            encoding="utf-8",
        )
        (docs_dir / "ARCHITECTURE.md").write_text(
            f"# Architecture: {project_name}\n\n"
            + "\n".join(f"- **{l}**" for l in blueprint.architecture_layers),
            encoding="utf-8",
        )
        (docs_dir / "ROADMAP.md").write_text(
            f"# Implementation Roadmap: {project_name}\n\n"
            + "\n".join(f"- **{m['milestone']}**: {m['description']}" for m in blueprint.roadmap_milestones),
            encoding="utf-8",
        )

        # 2. Write README
        (root / "README.md").write_text(
            f"# {project_name}\n\n{blueprint.idea_summary}\n\n"
            f"Generated autonomously by ZERO Project Builder.\n",
            encoding="utf-8",
        )

        # 3. Write requirements.txt
        (root / "requirements.txt").write_text("pytest>=8.0.0\npydantic>=2.0.0\n", encoding="utf-8")

        # 4. Write Core Package
        core_dir = root / f"{slug}_core"
        core_dir.mkdir(exist_ok=True)
        (core_dir / "__init__.py").write_text(f'"""Core package for {project_name}."""\n\n__version__ = "0.1.0"\n', encoding="utf-8")
        (core_dir / "config.py").write_text('"""Configuration module."""\n\nimport os\n\nPROJECT_NAME = "' + project_name + '"\n', encoding="utf-8")
        (core_dir / "orchestrator.py").write_text(
            '"""Domain orchestrator."""\n\nclass Orchestrator:\n    def run(self, task: str) -> dict:\n        return {"task": task, "status": "completed"}\n',
            encoding="utf-8",
        )

        # 5. Write Tests
        tests_dir = root / "tests"
        tests_dir.mkdir(exist_ok=True)
        (tests_dir / "__init__.py").write_text("", encoding="utf-8")
        (tests_dir / "test_core.py").write_text(
            f"from {slug}_core.orchestrator import Orchestrator\n\n"
            f"def test_{slug}_orchestrator():\n"
            f"    orch = Orchestrator()\n"
            f"    res = orch.run('test task')\n"
            f"    assert res['status'] == 'completed'\n",
            encoding="utf-8",
        )

        created_files = [str(p.relative_to(root)) for p in root.rglob("*") if p.is_file()]
        return {
            "success": True,
            "project_name": project_name,
            "root_path": str(root),
            "blueprint_id": blueprint.blueprint_id,
            "files_created_count": len(created_files),
            "files": created_files,
        }

    def validate_scaffold(self, target_dir: Path) -> Dict[str, Any]:
        """Validates that a scaffolded project satisfies completeness and syntax rules."""
        if not target_dir.exists() or not target_dir.is_dir():
            return {"valid": False, "error": f"Directory not found: {target_dir}"}

        required_docs = ["README.md", "docs/SRS.md", "docs/ARCHITECTURE.md", "docs/ROADMAP.md"]
        missing_docs = [doc for doc in required_docs if not (target_dir / doc).exists()]

        python_files = list(target_dir.rglob("*.py"))
        syntax_errors = []
        import ast
        for py_file in python_files:
            try:
                ast.parse(py_file.read_text(encoding="utf-8", errors="ignore"))
            except SyntaxError as exc:
                syntax_errors.append(f"{py_file.name}: {exc.msg} on line {exc.lineno}")

        is_valid = len(missing_docs) == 0 and len(syntax_errors) == 0 and len(python_files) >= 3
        return {
            "valid": is_valid,
            "missing_docs": missing_docs,
            "python_files_count": len(python_files),
            "syntax_errors": syntax_errors,
        }


# Global singleton instance
DEFAULT_PROJECT_BUILDER = ProjectBuilderAgent()
