"""Project Builder Agent for ZERO (Milestone M15).

Orchestrates the complete software engineering inception pipeline for new AI products:
Idea -> Requirements/SRS -> Architecture -> ADRs -> Folder Structure -> Roadmap.
"""

from __future__ import annotations

import uuid
from dataclasses import asdict, dataclass, field
from datetime import datetime, timezone
from typing import Any, Dict, List, Optional


@dataclass
class ProjectBlueprint:
    """Represents a fully structured project architectural blueprint."""
    blueprint_id: str
    project_name: str
    idea_summary: str
    srs_requirements: Dict[str, List[str]]
    architecture_layers: List[str]
    adrs: List[Dict[str, str]]
    folder_structure: List[str]
    roadmap_milestones: List[Dict[str, str]]
    created_at: str = field(
        default_factory=lambda: datetime.now(timezone.utc).isoformat()
    )

    def to_markdown(self) -> str:
        """Renders the blueprint as a full specification document."""
        lines = [
            f"# Architectural Blueprint: {self.project_name}",
            f"*Generated by ZERO Project Builder*: {self.created_at}",
            "",
            "## 1. Idea & Problem Definition",
            self.idea_summary,
            "",
            "## 2. Software Requirements Specification (SRS)",
            "### Functional Requirements:",
        ]
        for req in self.srs_requirements.get("functional", []):
            lines.append(f"- {req}")

        lines.append("\n### Non-Functional Requirements:")
        for req in self.srs_requirements.get("non_functional", []):
            lines.append(f"- {req}")

        lines.append("\n## 3. Core Architecture & Layers")
        for layer in self.architecture_layers:
            lines.append(f"- **{layer}**")

        lines.append("\n## 4. Architecture Decision Records (ADRs)")
        for adr in self.adrs:
            lines.append(f"### {adr.get('title', 'ADR')}")
            lines.append(f"- **Decision**: {adr.get('decision', '')}")
            lines.append(f"- **Rationale**: {adr.get('rationale', '')}")

        lines.append("\n## 5. Target Folder Structure")
        lines.append("```text")
        for f in self.folder_structure:
            lines.append(f)
        lines.append("```")

        lines.append("\n## 6. Implementation Roadmap")
        for m in self.roadmap_milestones:
            lines.append(f"- **{m.get('milestone', 'M')}**: {m.get('description', '')}")

        return "\n".join(lines)


class ProjectBuilderAgent:
    """Native Project Builder Agent executing the Idea -> Architecture -> Roadmap pipeline."""

    def generate_srs(self, project_name: str, idea: str) -> Dict[str, List[str]]:
        """Produces structured functional and non-functional requirements."""
        return {
            "functional": [
                f"FR-01: Core domain orchestration for {project_name}.",
                "FR-02: Deterministic, framework-independent business logic handlers.",
                "FR-03: Multi-channel intake interface (API / CLI / Webhook).",
                "FR-04: Secure credential management and least-privilege role boundaries.",
            ],
            "non_functional": [
                "NFR-PERF-01: Low-latency response times under 100ms for core routing.",
                "NFR-REL-01: 100% automated test coverage without network flakiness.",
                "NFR-SEC-01: Strict secret sanitization and audit logging.",
            ],
        }

    def generate_architecture_layers(self, project_name: str) -> List[str]:
        """Defines the clean architecture layered model."""
        return [
            f"Interface Layer (CLI / FastAPI / Webhook) for {project_name}",
            "Application & Orchestration Layer (State Machine / Task Coordinator)",
            "Domain & Business Logic Core (Pure Python, zero-external dependencies)",
            "Data & Integration Adapters (PostgreSQL / Redis / External APIs)",
            "Observability & Telemetry (Structured JSON Logging & Tracing)",
        ]

    def generate_adrs(self, project_name: str) -> List[Dict[str, str]]:
        """Generates standard ADRs for the new system."""
        return [
            {
                "title": "ADR-001: Clean Modular Architecture",
                "decision": f"Keep {project_name} decoupled into core domain vs integration adapters.",
                "rationale": "Allows painless testability with synthetic fixtures and zero mock hallucinations.",
            },
            {
                "title": "ADR-002: Least Privilege Security Model",
                "decision": "Enforce read-only roles and approval gates for mutating operations.",
                "rationale": "Prevents unauthorized mutations and maintains total user trust.",
            },
        ]

    def generate_folder_structure(self, project_name: str) -> List[str]:
        """Generates standard folder layout."""
        slug = project_name.lower().replace(" ", "_")
        return [
            f"{slug}/",
            f"├── {slug}_core/",
            "│   ├── config.py",
            "│   ├── orchestrator.py",
            "│   ├── domain/",
            "│   ├── adapters/",
            "│   └── interfaces/",
            "├── tests/",
            "├── docs/",
            "│   ├── SRS.md",
            "│   ├── ARCHITECTURE.md",
            "│   └── ROADMAP.md",
            "├── scripts/",
            "├── Dockerfile",
            "├── docker-compose.yml",
            "└── README.md",
        ]

    def generate_roadmap(self) -> List[Dict[str, str]]:
        """Produces standard milestone sequence."""
        return [
            {"milestone": "M1 — Formalization", "description": "SRS, Architecture, ADRs, Folder Structure."},
            {"milestone": "M2 — Core Logic", "description": "Deterministic domain engine and unit test suite."},
            {"milestone": "M3 — Integration Adapters", "description": "Database, external API, and tool connectors."},
            {"milestone": "M4 — Interface & Observability", "description": "FastAPI web endpoints and structured logging."},
            {"milestone": "M5 — Deployment", "description": "Containerization and background service runners."},
        ]

    def build_blueprint(self, project_name: str, idea: str) -> ProjectBlueprint:
        """Executes the full pipeline generating an end-to-end blueprint."""
        blueprint_id = f"bp_{uuid.uuid4().hex[:8]}"
        srs = self.generate_srs(project_name, idea)
        layers = self.generate_architecture_layers(project_name)
        adrs = self.generate_adrs(project_name)
        folders = self.generate_folder_structure(project_name)
        roadmap = self.generate_roadmap()

        return ProjectBlueprint(
            blueprint_id=blueprint_id,
            project_name=project_name,
            idea_summary=idea,
            srs_requirements=srs,
            architecture_layers=layers,
            adrs=adrs,
            folder_structure=folders,
            roadmap_milestones=roadmap,
        )


# Global singleton instance
DEFAULT_PROJECT_BUILDER = ProjectBuilderAgent()
